import Head from 'next/head'
import React from 'react'
import EngagementMain from '../components/Engagement/main'

const engagement = () => {
  return (
    <div>
      <Head>
        <title>Boost ME | Engagement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EngagementMain />
    </div>
  )
}

export default engagement
