import Head from 'next/head'
import HomeMain from '../components/home/Main'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boost ME | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeMain />
      </main>
    </div>
  )
}
