import Head from 'next/head'
import { HomeMain } from '../components/home/main'
import { useEffect } from 'react'
import axios from 'axios'

export default function Home() {
  useEffect(() => {
    axios
      .get('/api/locateme')
      .then(({ data }) => console.log({ data }))
      .catch((error) => console.log({ error }))
  })

  return (
    <div>
      <Head>
        <title>Boost ME | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeMain />
      </main>
    </div>
  )
}
