import Head from 'next/head'
import React from 'react'
import PublishingMain from '../components/publishing/main'

const publishing = () => {
  return (
    <div>
      <Head>
        <title>Boost N Boom | Publishing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PublishingMain />
    </div>
  )
}

export default publishing
