import Head from 'next/head'
import React from 'react'
const Dashboard = () => {
  return (
    <div>
      <Head>
        <title>Boost ME | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Dashboard
